#!/bin/bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

# Configure HAProxy to send traffic to web-01 and web-02 using round-robin
echo "frontend web
    bind *:80
    mode http
    default_backend app

backend app
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy


